### ISSUE TITLE
Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by zg9uagfv** [k-yle/rtsp-relay#11]
Setting up RTSP server on linux (x64)
/Software/Projects/rtsp-relay/test/setupTests.js:14
rtspServer.stdout.pipe(process.stdout);
                  ^

TypeError: Cannot read property 'pipe' of undefined
    at Object.<anonymous> (/Software/Projects/rtsp-relay/test/setupTests.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by k-yle** [comment]
Hi, the error you posted came from a file called `setupTests.js` 

this is probably because you ran `npm test`, which is only needed if you want to contribute to this module itself. In which case you might need to run `chmod u+x test/rtsp-simple-server`

If you just want to use the module to stream your own IP camera, you don't need that file.

**Comment by k-yle** [comment]
Hi, I didn't hear back from you so I'm going to close this. Please see [my comment above](#issuecomment-768103846)
