### ISSUE TITLE
React 18 -> Examle: Function components cannot have string refs

### ISSUE THREAD

**Issue by baur** [k-yle/rtsp-relay#167]
React example from [repo](https://github.com/k-yle/rtsp-relay/blob/main/examples/react.md) is not working on React18

```JS
import React, { useRef, useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import { loadPlayer } from 'rtsp-relay/browser';

const App: React.VFC = () => {
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvas.current) throw new Error('Ref is null');

    loadPlayer({
      url: 'ws://localhost:2000/api/stream/470',
      canvas: canvas.current,
    });
  }, []);

  return <canvas ref={canvas} />;
};

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

```
Warning: A string ref, "false", has been found within a strict mode tree. String refs are a source of potential 
bugs and should be avoided. We recommend using useRef() or createRef() instead. Learn more about using 
refs safely here: https://reactjs.org/link/strict-mode-string-ref
    at App (http://localhost:3000/static/js/bundle.js:33:51)
printWarning @ react-dom.development.js:86
2react-dom.development.js:14701 Uncaught Error: Function components cannot have string refs. We recommend using
 useRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref
    at coerceRef (react-dom.development.js:14701:1)
    at reconcileSingleElement (react-dom.development.js:15622:1)
    at reconcileChildFibers (react-dom.development.js:15678:1)
    at reconcileChildren (react-dom.development.js:19964:1)
    at mountIndeterminateComponent (react-dom.development.js:20996:1)
    at beginWork (react-dom.development.js:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)
react-dom.development.js:18572 The above error occurred in the <App> component:

    at App (http://localhost:3000/static/js/bundle.js:33:51)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18572
react-dom.development.js:26874 Uncaught Error: Function components cannot have string refs. We recommend using useRef()
 instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref
    at coerceRef (react-dom.development.js:14701:1)
    at reconcileSingleElement (react-dom.development.js:15622:1)
    at reconcileChildFibers (react-dom.development.js:15678:1)
    at reconcileChildren (react-dom.development.js:19964:1)
    at mountIndeterminateComponent (react-dom.development.js:20996:1)
    at beginWork (react-dom.development.js:22416:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
    at renderRootSync (react-dom.development.js:26390:1)
```

**Comment by baur** [comment]
sorry it not works also on React17
I got the same error!

```JS
import React, { useRef, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { loadPlayer } from 'rtsp-relay/browser';

const App: React.VFC = () => {
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvas.current) throw new Error('Ref is null');

    loadPlayer({
      url: 'ws://localhost:2000/api/stream/470',
      canvas: canvas.current,
    });
  }, []);

  return <canvas ref={canvas} />;
};

ReactDOM.render(<App />, document.getElementById('root'));
```
What is wrong?

**Comment by k-yle** [comment]
Works fine for me. [codesandbox](https://codesandbox.io/s/react-playground-forked-s93207?file=/index.js)

**Comment by baur** [comment]
> Works fine for me. [codesandbox](https://codesandbox.io/s/react-playground-forked-s93207?file=/index.js)

thank you, 
Working code ->

```JS
import React, { useRef, useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import { loadPlayer } from 'rtsp-relay/browser';

const App = () => {
  const canvas = useRef(null);

  useEffect(() => {
    if (!canvas.current) throw new Error("Ref is null");

    loadPlayer({
          url: "ws://localhost:2000/api/stream/470",
      canvas: canvas.current
    });
  }, []);

  return (
    <>
      Hi <canvas ref={canvas} />
    </>
  );
};

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);
```

**Comment by baur** [comment]
I'm using this code as a component for per camera

```JS
import React, { useRef, useEffect } from 'react';
import { loadPlayer } from 'rtsp-relay/browser';

const Camera = ({ cameraId }) => {
  const canvas = useRef(null);

  useEffect(() => {
    if (!canvas.current) throw new Error("Ref is null");

    loadPlayer({
      url: `ws://balrks:2000/api/stream/${cameraId}`,
      canvas: canvas.current
    });
  }, [cameraId]);

  return (
    <>
      <canvas ref={canvas} style={{ width: 372, height: 218 }} id={cameraId}/>
    </>
  );
};

export default Camera;
```
But  I've 2 problems:

1) Many js imports

![image](https://user-images.githubusercontent.com/2898361/170976790-4a088257-c271-4b08-8d72-8970b849d5b2.png)

2) Unstable work if cameras are more than 10 (in my case 20 cam)
